services:

  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: crud_app
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: crud_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_operations
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: